general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    color = rgba(050505ff)
    blur_passes = 3
    blur_size = 8
}

label {
    monitor =
    text = $USER
    color = rgba(ffffffff)
    font_size = 24
    font_family = Sans Serif
    position = 0, 84
    halign = center
    valign = center
}

label {
    monitor =
    text = 󰌾
    color = rgba(bb9af7ff)
    font_size = 42
    font_family = Symbols Nerd Font Mono
    position = 0, 140
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 360, 54
    outline_thickness = 1
    dots_size = 0.22
    dots_spacing = 0.18
    dots_center = true
    outer_color = rgba(bb9af7ff)
    inner_color = rgba(0c0d12ee)
    font_color = rgba(ffffffff)
    fail_color = rgba(ff5555ff)
    check_color = rgba(bb9af7ff)
    placeholder_text = Password
    fail_text = Authentication failed
    fade_on_empty = false
    position = 0, 8
    halign = center
    valign = center
}
